local map = vim.keymap.set
map("n", "<leader>pv", "<CMD>Ex<CR>", { silent = true, desc = "Launch Netrw" })
map("n", "<ESC>", "<CMD>noh<CR>", { silent = true, desc = "Clear search highlight" })
map("n", "<C-`>", "<CMD>split term://$SHELL<CR>", { silent = true, desc = "Launch terminal at bottom" })
map("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
map({ "n", "i" }, "<C-s>", "<CMD>w<CR>", { silent = true, desc = "Save file" })
map({ "n", "i" }, "<C-q>", "<CMD>q<CR>", { silent = true, desc = "Quit NeoVim" })
map("n", "<Up>", function()
  print("Press k to go up!")
end)
map("n", "<Down>", function()
  print("Press j to go down!")
end)
map("n", "<Left>", function()
  print("Press h to go left!")
end)
map("n", "<Right>", function()
  print("Press l to go right!")
end)
map("n", "<A-h>", "<C-w><C->>", { desc = "Increase width of the split" })
map("n", "<A-l>", "<C-w><C-<>", { desc = "Decrease width of the split" })
map("n", "<A-k>", "<C-w><C-+>", { desc = "Increase height of the split" })
map("n", "<A-j>", "<C-w><C-->", { desc = "Decrease height of the split" })
map("n", "<C-h>", "<C-w><C-h>", { desc = "Move cursor to left window" })
map("n", "<C-j>", "<C-w><C-j>", { desc = "Move cursor to bottom window" })
map("n", "<C-k>", "<C-w><C-k>", { desc = "Move cursor to top window" })
map("n", "<C-l>", "<C-w><C-l>", { desc = "Move cursor to right window" })
